{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "21406655",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting datasets\n",
      "  Downloading datasets-3.5.0-py3-none-any.whl.metadata (19 kB)\n",
      "Requirement already satisfied: filelock in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from datasets) (3.13.1)\n",
      "Requirement already satisfied: numpy>=1.17 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from datasets) (1.26.4)\n",
      "Requirement already satisfied: pyarrow>=15.0.0 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from datasets) (16.1.0)\n",
      "Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from datasets) (0.3.8)\n",
      "Requirement already satisfied: pandas in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from datasets) (2.2.2)\n",
      "Requirement already satisfied: requests>=2.32.2 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from datasets) (2.32.3)\n",
      "Requirement already satisfied: tqdm>=4.66.3 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from datasets) (4.66.5)\n",
      "Collecting xxhash (from datasets)\n",
      "  Downloading xxhash-3.5.0-cp310-cp310-win_amd64.whl.metadata (13 kB)\n",
      "Collecting multiprocess<0.70.17 (from datasets)\n",
      "  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)\n",
      "Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.6.1)\n",
      "Requirement already satisfied: aiohttp in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from datasets) (3.10.5)\n",
      "Requirement already satisfied: huggingface-hub>=0.24.0 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from datasets) (0.29.3)\n",
      "Requirement already satisfied: packaging in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from datasets) (24.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from datasets) (6.0.1)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from aiohttp->datasets) (2.4.0)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from aiohttp->datasets) (1.2.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from aiohttp->datasets) (23.1.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from aiohttp->datasets) (1.4.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from aiohttp->datasets) (6.0.4)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from aiohttp->datasets) (1.11.0)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from aiohttp->datasets) (4.0.3)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from requests>=2.32.2->datasets) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from requests>=2.32.2->datasets) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from requests>=2.32.2->datasets) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from requests>=2.32.2->datasets) (2024.8.30)\n",
      "Requirement already satisfied: colorama in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from pandas->datasets) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from pandas->datasets) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from pandas->datasets) (2023.3)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\sowmy\\.conda\\envs\\dev\\lib\\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)\n",
      "Downloading datasets-3.5.0-py3-none-any.whl (491 kB)\n",
      "Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)\n",
      "Downloading xxhash-3.5.0-cp310-cp310-win_amd64.whl (30 kB)\n",
      "Installing collected packages: xxhash, multiprocess, datasets\n",
      "Successfully installed datasets-3.5.0 multiprocess-0.70.16 xxhash-3.5.0\n"
     ]
    }
   ],
   "source": [
    "# !pip install python-dotenv\n",
    "# !pip install langchain_openai\n",
    "# !pip install langchain\n",
    "# !pip install langchain_community\n",
    "# !pip install jq\n",
    "# !pip install gdown\n",
    "# !pip install docarray\n",
    "!pip install datasets\n",
    "# %load_ext cudf.pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c52ce10b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import dask.dataframe as dd\n",
    "import gdown\n",
    "import re\n",
    "import numpy as np\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "4bd67dd3",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Downloading...\n",
      "From (original): https://drive.google.com/uc?export=download&id=14GcJAzyN2PFg2JuyzF0pRmxlMmimrz9o\n",
      "From (redirected): https://drive.google.com/uc?export=download&id=14GcJAzyN2PFg2JuyzF0pRmxlMmimrz9o&confirm=t&uuid=53bfbac2-7dec-4f96-88f7-9381a2e5b0dd\n",
      "To: c:\\Sowmya\\Code\\CapstoneProject-AI-Class\\AmazonHomeKitchenReviews.csv\n",
      "100%|██████████| 692M/692M [02:48<00:00, 4.11MB/s] \n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "'AmazonHomeKitchenReviews.csv'"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "amazonhkdatasetfileid = '14GcJAzyN2PFg2JuyzF0pRmxlMmimrz9o'\n",
    "amazonhkdatasetfilename = 'AmazonHomeKitchenReviews.csv'\n",
    "\n",
    "url = f\"https://drive.google.com/uc?export=download&id={amazonhkdatasetfileid}\"\n",
    "\n",
    "gdown.download(url,amazonhkdatasetfilename, quiet=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "3a0956e6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "91691"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_data = pd.read_csv(amazonhkdatasetfilename)\n",
    "#df_data = df_data.head(10000)\n",
    "df_filtered = df_data[df_data['categories'] == \"['Home & Kitchen', 'Bedding', 'Sheets & Pillowcases', 'Sheet & Pillowcase Sets']\"]\n",
    "len(df_filtered)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "0af68280",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['Unnamed: 0', 'rating', 'review_title', 'review_text', 'images', 'asin',\n",
      "       'parent_asin', 'user_id', 'timestamp', 'helpful_vote',\n",
      "       'verified_purchase', 'product_title', 'description', 'price', 'Brand',\n",
      "       'Material', 'Color', 'categories'],\n",
      "      dtype='object')\n"
     ]
    }
   ],
   "source": [
    "df_renamed = df_filtered.rename(columns={'title_y' : 'product_title','title_x':'review_title','text':'review_text'})\n",
    "df_renamed.groupby('product_title').size().sort_values(ascending=False).head(5)\n",
    "print(df_renamed.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "86e9ad83",
   "metadata": {},
   "outputs": [],
   "source": [
    "qa_pairs = []\n",
    "for index , row in df_renamed.iterrows():\n",
    "  context = str(row['review_title']) + \". \" + str(row[\"review_text\"]) + \" \" + \"$\" + str(row['price']) + \". \" + str(row['rating']) +\" \" +  str(row['product_title'])\n",
    "  #print(context\n",
    "\n",
    "    # Generate questions about user rating only if rating is not null\n",
    "  if not pd.isna(row['rating']):\n",
    "        qa_pairs.append({\n",
    "            'context': context,\n",
    "            'question': f\"What was the average rating for product{str(row['product_title'])}?\",\n",
    "          #  'answer' : str(row['rating'])\n",
    "            'answer': {'text': str(row['rating']), 'answer_start': context.find(str(row['rating'])) if str(row['rating']) in context else 0}\n",
    "\n",
    "        })\n",
    "\n",
    "        # Question about why they gave that rating\n",
    "        qa_pairs.append({\n",
    "            'context': context,\n",
    "            'question': f\"Why did the customer rate this product {str(row['rating'])} stars?\",\n",
    "             'answer': {'text': context[:150], 'answer_start': 0}\n",
    "        })\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "fa5443e4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "dict_keys(['train', 'test'])\n",
      "{'context': \"Comfort. The sheet set was just what I wanted! They're great! Thanks $38.99. 5 Full Size Sheet Set - 6 Piece Set - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - Breathable & Cooling Sheets - Wrinkle Free - Comfy - Beige Tan Bed Sheets - Fulls Sheets - 6 PC\", 'question': 'What was the average rating for productFull Size Sheet Set - 6 Piece Set - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - Breathable & Cooling Sheets - Wrinkle Free - Comfy - Beige Tan Bed Sheets - Fulls Sheets - 6 PC?', 'answer': {'answer_start': 77, 'text': '5'}}\n"
     ]
    }
   ],
   "source": [
    "from datasets import Dataset\n",
    "\n",
    "dataset = Dataset.from_list(qa_pairs)\n",
    "dataset = dataset.train_test_split(test_size=0.2)\n",
    "\n",
    "print(dataset.keys())\n",
    "print(dataset['test'][0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "55303302",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Device set to use cpu\n"
     ]
    }
   ],
   "source": [
    "from transformers import AutoModelForQuestionAnswering, AutoTokenizer, pipeline\n",
    "# Load your fine-tuned model and tokenizer\n",
    "model = AutoModelForQuestionAnswering.from_pretrained(\"Resources/finetunedmodel\")\n",
    "tokenizer = AutoTokenizer.from_pretrained(\"Resources/finetunedmodel\")\n",
    "qa_pipeline = pipeline(\"question-answering\", model=model, tokenizer=tokenizer)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "db3dca55",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dataset({\n",
      "    features: ['context', 'question', 'answer'],\n",
      "    num_rows: 100\n",
      "})\n"
     ]
    }
   ],
   "source": [
    "evaluatetest = dataset['test'].select(range(100))\n",
    "print(evaluatetest)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "2c43a3ad",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Predicted Answer (raw): {'score': 0.9991750121116638, 'start': 77, 'end': 78, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 77, 'text': '5'}\n",
      "Question: What was the average rating for productFull Size Sheet Set - 6 Piece Set - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - Breathable & Cooling Sheets - Wrinkle Free - Comfy - Beige Tan Bed Sheets - Fulls Sheets - 6 PC?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0003041128220502287, 'start': 0, 'end': 4, 'answer': 'Five'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Five Stars. Sheets very soft, deep pockets will help keep fitted on! $24.99. 5 1500 Supreme Collection Twin XL Sheet Sets Lilac - 3 Piece Bed Sheets a'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Five Stars. Sheets very soft, deep pockets will help keep fitted on! $24.99. 5 1500 Supreme Collection Twin XL Sheet Sets Lilac - 3 Piece Bed Sheets a\n",
      "Predicted Answer: Five\n",
      "F1 Score: 0.07142857142857142, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00013468333054333925, 'start': 146, 'end': 152, 'answer': 'Luxury'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Awesome quality at a great price!. So comfortable and soft. I love this sheet set!!! $34.99. 5 King Size Sheet Set - Breathable & Cooling - Hotel Luxu'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Awesome quality at a great price!. So comfortable and soft. I love this sheet set!!! $34.99. 5 King Size Sheet Set - Breathable & Cooling - Hotel Luxu\n",
      "Predicted Answer: Luxury\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00023636770492885262, 'start': 0, 'end': 3, 'answer': 'NOT'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'NOT BAD.. Love These, BUT Quality Of Material Is Thin. These Are Exspensive For The Quality In Fabric. $24.99. 4 1500 Supreme Collection Twin XL Sheet'}\n",
      "Question: Why did the customer rate this product 4 stars?\n",
      "True Answer: NOT BAD.. Love These, BUT Quality Of Material Is Thin. These Are Exspensive For The Quality In Fabric. $24.99. 4 1500 Supreme Collection Twin XL Sheet\n",
      "Predicted Answer: NOT\n",
      "F1 Score: 0.07692307692307693, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00019556032202672213, 'start': 0, 'end': 2, 'answer': 'It'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'It’s still polyester any traps moisture.. My friend said it was soft so I bought it but it’s 100% polyester:(  I forgot to read it All the way through'}\n",
      "Question: Why did the customer rate this product 2 stars?\n",
      "True Answer: It’s still polyester any traps moisture.. My friend said it was soft so I bought it but it’s 100% polyester:(  I forgot to read it All the way through\n",
      "Predicted Answer: It\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00017131037020590156, 'start': 0, 'end': 4, 'answer': 'Soft'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': \"Soft and Breathable. This sheet set, queen-purple, is very soft and light. It's a deep purple and I really am glad with this purchase. $34.99. 5 King \"}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Soft and Breathable. This sheet set, queen-purple, is very soft and light. It's a deep purple and I really am glad with this purchase. $34.99. 5 King \n",
      "Predicted Answer: Soft\n",
      "F1 Score: 0.07692307692307693, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00019852006516885012, 'start': 0, 'end': 4, 'answer': 'Very'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Very soft. Sheets are very soft. Washed and they sat for a couple of days before going on the guest bed. Wrinkle free. They are a little thin but perf'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Very soft. Sheets are very soft. Washed and they sat for a couple of days before going on the guest bed. Wrinkle free. They are a little thin but perf\n",
      "Predicted Answer: Very\n",
      "F1 Score: 0.07142857142857142, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9990349411964417, 'start': 179, 'end': 180, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 179, 'text': '5'}\n",
      "Question: What was the average rating for productShilucheng Bed Sheet Set Microfiber 1800 Threads Egyptian Super Soft Sheets 16-Inch Deep Pocket - Hypoallergenic - 6 Piece (Grey, Twin XL)?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0001626819430384785, 'start': 0, 'end': 4, 'answer': 'High'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'High quality!. These sheets have super deep pocket, and are very well made. High quality material. Gets softer with every wash.  10/10 will buy again!'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: High quality!. These sheets have super deep pocket, and are very well made. High quality material. Gets softer with every wash.  10/10 will buy again!\n",
      "Predicted Answer: High\n",
      "F1 Score: 0.07999999999999999, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00010720383579609916, 'start': 150, 'end': 157, 'answer': 'pockets'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Light, soft and wrinkle free sheets!. Very pleased with these sheets. They came out of the dryer wrinkle free and soft.  I particularly like the deep '}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Light, soft and wrinkle free sheets!. Very pleased with these sheets. They came out of the dryer wrinkle free and soft.  I particularly like the deep \n",
      "Predicted Answer: pockets\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9991330504417419, 'start': 99, 'end': 100, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 99, 'text': '5'}\n",
      "Question: What was the average rating for productElegant Comfort Luxury Soft Bed Sheets 1500 Thread Count Percale Egyptian Quality Softness Wrinkle and Fade Resistant (6-Piece) Bedding Set, Full, Aqua Blue?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9945166707038879, 'start': 477, 'end': 478, 'answer': '4'}\n",
      "True Answer (raw): {'answer_start': 477, 'text': '4'}\n",
      "Question: What was the average rating for productShilucheng Bed Sheet Set Microfiber 1800 Threads Egyptian Super Soft Sheets 16-Inch Deep Pocket - Hypoallergenic - 6 Piece (Grey, Twin XL)?\n",
      "True Answer: 4\n",
      "Predicted Answer: 4\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.8873122334480286, 'start': 34, 'end': 35, 'answer': '1'}\n",
      "True Answer (raw): {'answer_start': 34, 'text': '1'}\n",
      "Question: What was the average rating for productBare Home Queen Sheet Set - 6 Piece Set - Hotel Luxury Bed Sheets - Ultra Soft - Deep Pockets - Easy Fit - Cooling & Breathable Sheets - Wrinkle Resistant - Cozy - Cream - Queen Sheets - 6 PC?\n",
      "True Answer: 1\n",
      "Predicted Answer: 1\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.996973991394043, 'start': 30, 'end': 31, 'answer': '4'}\n",
      "True Answer (raw): {'answer_start': 30, 'text': '4'}\n",
      "Question: What was the average rating for productAmazon Basics Lightweight Super Soft Easy Care Microfiber Bed Sheet Set with Two Pillowcases - Twin, Bright White?\n",
      "True Answer: 4\n",
      "Predicted Answer: 4\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00019455593428574502, 'start': 0, 'end': 5, 'answer': 'Great'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Great. Sheets are amazing so soft $27.99. 5 Mejoroom Full Size Sheet Set,Extra Soft Luxury Brushed Microfiber 1800 Full Sheets with 16 Inch Deep Pocke'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Great. Sheets are amazing so soft $27.99. 5 Mejoroom Full Size Sheet Set,Extra Soft Luxury Brushed Microfiber 1800 Full Sheets with 16 Inch Deep Pocke\n",
      "Predicted Answer: Great\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9992527365684509, 'start': 696, 'end': 697, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 696, 'text': '5'}\n",
      "Question: What was the average rating for productMellanni RV Bedding Short Queen - Double Brushed Microfiber Camper Bunk Sheets - Durable and Breathable Cooling Sheets - Fits Mattress Up to 10'' - Deep Pocket Queen Sheet Sets (Short Queen, Spa Blue)?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9995051026344299, 'start': 138, 'end': 139, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 138, 'text': '5'}\n",
      "Question: What was the average rating for productBASIC CHOICE Brushed Microfiber Bed Sheet Set, Teal, California King 4 Pieces?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00022005282517056912, 'start': 0, 'end': 5, 'answer': 'Great'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Great value and great price. These sheets are amazingly soft and the price is incredible.  So pleasantly surprised with the that I will be ordering mo'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Great value and great price. These sheets are amazingly soft and the price is incredible.  So pleasantly surprised with the that I will be ordering mo\n",
      "Predicted Answer: Great\n",
      "F1 Score: 0.07999999999999999, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9994412064552307, 'start': 70, 'end': 71, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 70, 'text': '5'}\n",
      "Question: What was the average rating for productHOMEIDEAS 6 Piece Bed Sheets Set Extra Soft Brushed Microfiber 1800 Bedding Sheets Deep Pocket, Wrinkle & Fade Free (King,Black)?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9992952346801758, 'start': 98, 'end': 99, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 98, 'text': '5'}\n",
      "Question: What was the average rating for product1500 Supreme Collection Twin XL Sheet Sets Lilac - 3 Piece Bed Sheets and Pillowcase Set for Twin XL Mattress - Extra Soft, Elastic Corner Straps, Deep Pocket Sheets, Twin XL Lilac?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0003366713644936681, 'start': 0, 'end': 4, 'answer': 'Best'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Best sheets I’ve ever bought.... I’m 65 years old and love to shop for quality items. These are the best sheets I’ve ever owned. Reasonable priced, wr'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Best sheets I’ve ever bought.... I’m 65 years old and love to shop for quality items. These are the best sheets I’ve ever owned. Reasonable priced, wr\n",
      "Predicted Answer: Best\n",
      "F1 Score: 0.07999999999999999, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.999667227268219, 'start': 273, 'end': 275, 'answer': '34'}\n",
      "True Answer (raw): {'answer_start': 274, 'text': '4'}\n",
      "Question: What was the average rating for productMellanni RV Bedding Short Queen - Double Brushed Microfiber Camper Bunk Sheets - Durable and Breathable Cooling Sheets - Fits Mattress Up to 10'' - Deep Pocket Queen Sheet Sets (Short Queen, Spa Blue)?\n",
      "True Answer: 4\n",
      "Predicted Answer: 34\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00021922081941738725, 'start': 0, 'end': 7, 'answer': 'Amazing'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Amazing sbeet5. Love these sheets, the colors, the softness and the price for the comfort is amazing. $27.99. 5 Mejoroom Full Size Sheet Set,Extra Sof'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Amazing sbeet5. Love these sheets, the colors, the softness and the price for the comfort is amazing. $27.99. 5 Mejoroom Full Size Sheet Set,Extra Sof\n",
      "Predicted Answer: Amazing\n",
      "F1 Score: 0.08695652173913045, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00013935795868746936, 'start': 0, 'end': 4, 'answer': 'Five'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Five Stars. One of the best sheet sets ever! Great value! $64.99. 5 Stripe Taupe Queen Size Sheets, 4PC Bed Sheet Set, 100% Cotton, 300 Thread Count, '}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Five Stars. One of the best sheet sets ever! Great value! $64.99. 5 Stripe Taupe Queen Size Sheets, 4PC Bed Sheet Set, 100% Cotton, 300 Thread Count, \n",
      "Predicted Answer: Five\n",
      "F1 Score: 0.07142857142857142, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9984262585639954, 'start': 185, 'end': 187, 'answer': '34'}\n",
      "True Answer (raw): {'answer_start': 186, 'text': '4'}\n",
      "Question: What was the average rating for productMellanni RV Bedding Short Queen - Double Brushed Microfiber Camper Bunk Sheets - Durable and Breathable Cooling Sheets - Fits Mattress Up to 10'' - Deep Pocket Queen Sheet Sets (Short Queen, Spa Blue)?\n",
      "True Answer: 4\n",
      "Predicted Answer: 34\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.591637372970581, 'start': 195, 'end': 197, 'answer': '34'}\n",
      "True Answer (raw): {'answer_start': 195, 'text': '3'}\n",
      "Question: What was the average rating for productClara Clark 1800 Premier Series 4pc Bed Sheet Set - King, Purple Eggplant?\n",
      "True Answer: 3\n",
      "Predicted Answer: 34\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00012067412171745673, 'start': 0, 'end': 4, 'answer': 'Nice'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Nice sheets,  I will order more.. Nice sheets,  I will order more. $34.97. 5 Mellanni RV Bedding Short Queen - Double Brushed Microfiber Camper Bunk S'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Nice sheets,  I will order more.. Nice sheets,  I will order more. $34.97. 5 Mellanni RV Bedding Short Queen - Double Brushed Microfiber Camper Bunk S\n",
      "Predicted Answer: Nice\n",
      "F1 Score: 0.0909090909090909, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9994798302650452, 'start': 25, 'end': 26, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 25, 'text': '5'}\n",
      "Question: What was the average rating for productQueen Sheets Silver - 6 Piece 1500 Supreme Collection Fine Brushed Microfiber Deep Pocket Queen Sheet Set Bedding - 2 Extra Pillow Cases, Great Value, Queen, Silver?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0001766132772900164, 'start': 152, 'end': 158, 'answer': 'Cotton'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Super high quality. Beautiful sheets, nice details. Great quality. $107.99. 5 QSH Floral King Size Sheet Sets - Flower Butterfly Print Pattern Egyptia'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Super high quality. Beautiful sheets, nice details. Great quality. $107.99. 5 QSH Floral King Size Sheet Sets - Flower Butterfly Print Pattern Egyptia\n",
      "Predicted Answer: Cotton\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0002504214062355459, 'start': 0, 'end': 4, 'answer': 'Soft'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Soft, comfortable sheets. Love these sheets. Fit well, wash well, dry wrinkle free. Soft and comfortable! $34.99. 5 King Size Sheet Set - Breathable &'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Soft, comfortable sheets. Love these sheets. Fit well, wash well, dry wrinkle free. Soft and comfortable! $34.99. 5 King Size Sheet Set - Breathable &\n",
      "Predicted Answer: Soft\n",
      "F1 Score: 0.08333333333333333, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9989882111549377, 'start': 123, 'end': 124, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 123, 'text': '5'}\n",
      "Question: What was the average rating for productKing Size Sheet Set - Breathable & Cooling - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - 4 Piece Set - Wrinkle Free - Comfy - Dark Grey Bed Sheets - Kings Sheets - Fitted Sheets?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9996333122253418, 'start': 91, 'end': 92, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 91, 'text': '5'}\n",
      "Question: What was the average rating for productAmazon Basics Lightweight Super Soft Easy Care Microfiber Bed Sheet Set with Two Pillowcases - Twin, Bright White?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0006102410843595862, 'start': 0, 'end': 4, 'answer': 'Five'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Five Stars. I just received this order and I really like the softness of these sheets. $24.99. 5 1500 Supreme Collection Twin XL Sheet Sets Lilac - 3 '}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Five Stars. I just received this order and I really like the softness of these sheets. $24.99. 5 1500 Supreme Collection Twin XL Sheet Sets Lilac - 3 \n",
      "Predicted Answer: Five\n",
      "F1 Score: 0.07142857142857142, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0001339089940302074, 'start': 0, 'end': 4, 'answer': 'Love'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Love! ❤️. The deep pockets in the fitted sheet fit the mattress perfectly. I absolutely love these sheets.  They are nothing like the microfiber slipp'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Love! ❤️. The deep pockets in the fitted sheet fit the mattress perfectly. I absolutely love these sheets.  They are nothing like the microfiber slipp\n",
      "Predicted Answer: Love\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00030219138716347516, 'start': 0, 'end': 4, 'answer': 'Nice'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': \"Nice. I've only had on my bed for 2 days . Time will tell. But so far so good. $38.99. 5 Full Size Sheet Set - 6 Piece Set - Hotel Luxury Bed Sheets -\"}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Nice. I've only had on my bed for 2 days . Time will tell. But so far so good. $38.99. 5 Full Size Sheet Set - 6 Piece Set - Hotel Luxury Bed Sheets -\n",
      "Predicted Answer: Nice\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9997453689575195, 'start': 85, 'end': 86, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 85, 'text': '5'}\n",
      "Question: What was the average rating for productAmazon Basics Lightweight Super Soft Easy Care Microfiber Bed Sheet Set with Two Pillowcases - Twin, Bright White?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9997867345809937, 'start': 362, 'end': 363, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 362, 'text': '5'}\n",
      "Question: What was the average rating for productAmazon Basics Lightweight Super Soft Easy Care Microfiber Bed Sheet Set with Two Pillowcases - Twin, Bright White?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00015689354040659964, 'start': 0, 'end': 4, 'answer': 'Will'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Will buy more. Fits very well and very soft and comfortable $29.69. 5 LBRO2M Bed Sheets Set King Size 6 Piece 16 Inches Deep Pocket 1800 Thread Count '}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Will buy more. Fits very well and very soft and comfortable $29.69. 5 LBRO2M Bed Sheets Set King Size 6 Piece 16 Inches Deep Pocket 1800 Thread Count \n",
      "Predicted Answer: Will\n",
      "F1 Score: 0.07407407407407407, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0002917765232268721, 'start': 0, 'end': 4, 'answer': 'Very'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Very soft! Great quality!. Super soft! The best sheets ever! Will purchase more! $35.99. 5 EASELAND Queen Sheets Cotton, White Cotton Sheets Queen -10'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Very soft! Great quality!. Super soft! The best sheets ever! Will purchase more! $35.99. 5 EASELAND Queen Sheets Cotton, White Cotton Sheets Queen -10\n",
      "Predicted Answer: Very\n",
      "F1 Score: 0.0909090909090909, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00016052696446422487, 'start': 0, 'end': 1, 'answer': 'I'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'I like the green color. The softness is incredible!! $34.99. 5 King Size Sheet Set - Breathable & Cooling - Hotel Luxury Bed Sheets - Extra Soft - Dee'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: I like the green color. The softness is incredible!! $34.99. 5 King Size Sheet Set - Breathable & Cooling - Hotel Luxury Bed Sheets - Extra Soft - Dee\n",
      "Predicted Answer: I\n",
      "F1 Score: 0.07407407407407407, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9994604587554932, 'start': 74, 'end': 75, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 74, 'text': '5'}\n",
      "Question: What was the average rating for productKing Size Sheet Set - Breathable & Cooling - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - 4 Piece Set - Wrinkle Free - Comfy - Dark Grey Bed Sheets - Kings Sheets - Fitted Sheets?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00034678232623264194, 'start': 0, 'end': 4, 'answer': 'Very'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Very nice and soft. Very nice and soft. Purchased for my daughter so I have not removed it from package yet. Will change my review only if things are '}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Very nice and soft. Very nice and soft. Purchased for my daughter so I have not removed it from package yet. Will change my review only if things are \n",
      "Predicted Answer: Very\n",
      "F1 Score: 0.07999999999999999, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00013620003301184624, 'start': 0, 'end': 7, 'answer': 'Perfect'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Perfect. So smooth! These wash nicely, hold their color and are so nice to sleep on. $22.83. 5 Elegant Comfort ® 1500 Thread Count Egyptian Quality Su'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Perfect. So smooth! These wash nicely, hold their color and are so nice to sleep on. $22.83. 5 Elegant Comfort ® 1500 Thread Count Egyptian Quality Su\n",
      "Predicted Answer: Perfect\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9993650317192078, 'start': 87, 'end': 88, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 87, 'text': '5'}\n",
      "Question: What was the average rating for productKing Size Sheet Set - Breathable & Cooling - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - 4 Piece Set - Wrinkle Free - Comfy - Dark Grey Bed Sheets - Kings Sheets - Fitted Sheets?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9992756843566895, 'start': 107, 'end': 108, 'answer': '2'}\n",
      "True Answer (raw): {'answer_start': 107, 'text': '2'}\n",
      "Question: What was the average rating for productMellanni RV Bedding Short Queen - Double Brushed Microfiber Camper Bunk Sheets - Durable and Breathable Cooling Sheets - Fits Mattress Up to 10'' - Deep Pocket Queen Sheet Sets (Short Queen, Spa Blue)?\n",
      "True Answer: 2\n",
      "Predicted Answer: 2\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.999385416507721, 'start': 162, 'end': 163, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 162, 'text': '5'}\n",
      "Question: What was the average rating for productQueen Sheets Silver - 6 Piece 1500 Supreme Collection Fine Brushed Microfiber Deep Pocket Queen Sheet Set Bedding - 2 Extra Pillow Cases, Great Value, Queen, Silver?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00028744337032549083, 'start': 0, 'end': 4, 'answer': 'good'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'good sheets. comfortable, works fine $38.99. 4 Full Size Sheet Set - 6 Piece Set - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - Br'}\n",
      "Question: Why did the customer rate this product 4 stars?\n",
      "True Answer: good sheets. comfortable, works fine $38.99. 4 Full Size Sheet Set - 6 Piece Set - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - Br\n",
      "Predicted Answer: good\n",
      "F1 Score: 0.07692307692307693, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0001559313532197848, 'start': 0, 'end': 5, 'answer': 'Great'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Great product and value.. These sheets are really nice and an amazing value for the price.  They are like a hug from your bed every night. $24.99. 5 1'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Great product and value.. These sheets are really nice and an amazing value for the price.  They are like a hug from your bed every night. $24.99. 5 1\n",
      "Predicted Answer: Great\n",
      "F1 Score: 0.07142857142857142, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00021748400467913598, 'start': 0, 'end': 4, 'answer': 'Nice'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Nice. I use these for  a rental cabin. Guest say they are soft. They wash up easy and clean $21.99. 5 Shilucheng Bed Sheet Set Microfiber 1800 Threads'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Nice. I use these for  a rental cabin. Guest say they are soft. They wash up easy and clean $21.99. 5 Shilucheng Bed Sheet Set Microfiber 1800 Threads\n",
      "Predicted Answer: Nice\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.3462068736553192, 'start': 110, 'end': 111, 'answer': '4'}\n",
      "True Answer (raw): {'answer_start': 110, 'text': '4'}\n",
      "Question: What was the average rating for productLinen Market Ultra Soft Easy Care Microfiber 16\" Deep Pocket Basic 4 Piece Bed Sheet Set with Pillowcases, Ivory, California King?\n",
      "True Answer: 4\n",
      "Predicted Answer: 4\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9880765080451965, 'start': 217, 'end': 218, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 217, 'text': '5'}\n",
      "Question: What was the average rating for productMellanni RV Bedding Short Queen - Double Brushed Microfiber Camper Bunk Sheets - Durable and Breathable Cooling Sheets - Fits Mattress Up to 10'' - Deep Pocket Queen Sheet Sets (Short Queen, Spa Blue)?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9995325207710266, 'start': 240, 'end': 241, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 240, 'text': '5'}\n",
      "Question: What was the average rating for product1500 Supreme Collection Twin XL Sheet Sets Lilac - 3 Piece Bed Sheets and Pillowcase Set for Twin XL Mattress - Extra Soft, Elastic Corner Straps, Deep Pocket Sheets, Twin XL Lilac?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0001081507871276699, 'start': 0, 'end': 5, 'answer': 'Great'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Great looking. Great looking and soft comfy to sleep on $28.9. 5 SONORO KATE Bed Sheet Set Super Soft Microfiber 1800 Thread Count Luxury Egyptian She'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Great looking. Great looking and soft comfy to sleep on $28.9. 5 SONORO KATE Bed Sheet Set Super Soft Microfiber 1800 Thread Count Luxury Egyptian She\n",
      "Predicted Answer: Great\n",
      "F1 Score: 0.07692307692307693, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9994591474533081, 'start': 90, 'end': 91, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 90, 'text': '5'}\n",
      "Question: What was the average rating for productMellanni RV Bedding Short Queen - Double Brushed Microfiber Camper Bunk Sheets - Durable and Breathable Cooling Sheets - Fits Mattress Up to 10'' - Deep Pocket Queen Sheet Sets (Short Queen, Spa Blue)?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00012401051935739815, 'start': 0, 'end': 4, 'answer': 'Very'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Very soft and well made product. The only reason .... Very soft and well made product. The only reason for the four stars is the &#34;burgandy&#34; co'}\n",
      "Question: Why did the customer rate this product 4 stars?\n",
      "True Answer: Very soft and well made product. The only reason .... Very soft and well made product. The only reason for the four stars is the &#34;burgandy&#34; co\n",
      "Predicted Answer: Very\n",
      "F1 Score: 0.1111111111111111, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9973354935646057, 'start': 45, 'end': 46, 'answer': '4'}\n",
      "True Answer (raw): {'answer_start': 45, 'text': '4'}\n",
      "Question: What was the average rating for productTwin Sheets - Breathable Luxury Sheets with Full Elastic & Secure Corner Straps Built In - 1800 Supreme Collection Extra Soft Deep Pocket Bedding Set, Fitted Sheet Only, Twin, Black?\n",
      "True Answer: 4\n",
      "Predicted Answer: 4\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9988844990730286, 'start': 36, 'end': 37, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 36, 'text': '5'}\n",
      "Question: What was the average rating for productUtopia Bedding King Sheet Set - Jersey Knit Sheets 4 Piece King Jersey Sheet Set – Cotton Jersey Sheets – Soft T-Shirt Stretchy Sheets (King, Dark Grey)?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0001614507636986673, 'start': 0, 'end': 4, 'answer': 'Soft'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Soft and warm. Very satisfied with these sheets...very warm...like sleeping on a warm cloud.  Great buy! $43.79. 5 Sleep Philosophy True North Micro F'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Soft and warm. Very satisfied with these sheets...very warm...like sleeping on a warm cloud.  Great buy! $43.79. 5 Sleep Philosophy True North Micro F\n",
      "Predicted Answer: Soft\n",
      "F1 Score: 0.07999999999999999, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.2850452661514282, 'start': 154, 'end': 156, 'answer': '38'}\n",
      "True Answer (raw): {'answer_start': 154, 'text': '3'}\n",
      "Question: What was the average rating for productFull Size Sheet Set - 6 Piece Set - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - Breathable & Cooling Sheets - Wrinkle Free - Comfy - Beige Tan Bed Sheets - Fulls Sheets - 6 PC?\n",
      "True Answer: 3\n",
      "Predicted Answer: 38\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00024408036551903933, 'start': 0, 'end': 4, 'answer': 'Beat'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Beat brand. Nice quality, soft, comfortable to sleep with $28.01. 5 Amazon Basics Lightweight Super Soft Easy Care Microfiber Bed Sheet Set with Two P'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Beat brand. Nice quality, soft, comfortable to sleep with $28.01. 5 Amazon Basics Lightweight Super Soft Easy Care Microfiber Bed Sheet Set with Two P\n",
      "Predicted Answer: Beat\n",
      "F1 Score: 0.07999999999999999, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9994704127311707, 'start': 115, 'end': 116, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 115, 'text': '5'}\n",
      "Question: What was the average rating for product1500 Supreme Collection Twin XL Sheet Sets Lilac - 3 Piece Bed Sheets and Pillowcase Set for Twin XL Mattress - Extra Soft, Elastic Corner Straps, Deep Pocket Sheets, Twin XL Lilac?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0023967293091118336, 'start': 113, 'end': 121, 'answer': 'Eggplant'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Two Stars. Does not fit bed correctly $23.47. 2 Clara Clark 1800 Premier Series 4pc Bed Sheet Set - King, Purple Eggplant'}\n",
      "Question: Why did the customer rate this product 2 stars?\n",
      "True Answer: Two Stars. Does not fit bed correctly $23.47. 2 Clara Clark 1800 Premier Series 4pc Bed Sheet Set - King, Purple Eggplant\n",
      "Predicted Answer: Eggplant\n",
      "F1 Score: 0.08695652173913045, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00017862534150481224, 'start': 0, 'end': 2, 'answer': 'If'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'If you like soft, you will like these sheets. My husband says they are too lightweight and he doesn’t like anything flimsy. He is used to 1000 thread '}\n",
      "Question: Why did the customer rate this product 1 stars?\n",
      "True Answer: If you like soft, you will like these sheets. My husband says they are too lightweight and he doesn’t like anything flimsy. He is used to 1000 thread \n",
      "Predicted Answer: If\n",
      "F1 Score: 0.07692307692307693, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00013887548993807286, 'start': 0, 'end': 4, 'answer': 'Best'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Best Sheets Ever. This is my 2nd set of these sheets!! High end feel at a low price!!! I love them!!! $28.01. 5 Amazon Basics Lightweight Super Soft E'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Best Sheets Ever. This is my 2nd set of these sheets!! High end feel at a low price!!! I love them!!! $28.01. 5 Amazon Basics Lightweight Super Soft E\n",
      "Predicted Answer: Best\n",
      "F1 Score: 0.06666666666666667, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0006416798569262028, 'start': 0, 'end': 4, 'answer': 'BEST'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'BEST SHEETS EVER. These are the softest sheets and best sheets I’ve ever had! My only regret is not finding these sooner. $34.99. 5 King Size Sheet Se'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: BEST SHEETS EVER. These are the softest sheets and best sheets I’ve ever had! My only regret is not finding these sooner. $34.99. 5 King Size Sheet Se\n",
      "Predicted Answer: BEST\n",
      "F1 Score: 0.07142857142857142, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0002676266012713313, 'start': 0, 'end': 8, 'answer': 'Favorite'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Favorite despite minor imperfections. Love these new sheets. Fabric is so soft and comfortable. Love the color and pattern.<br /><br />Cons:<br />-Imp'}\n",
      "Question: Why did the customer rate this product 4 stars?\n",
      "True Answer: Favorite despite minor imperfections. Love these new sheets. Fabric is so soft and comfortable. Love the color and pattern.<br /><br />Cons:<br />-Imp\n",
      "Predicted Answer: Favorite\n",
      "F1 Score: 0.09523809523809523, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00042521997238509357, 'start': 141, 'end': 146, 'answer': 'White'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Soft and durable. Soft $28.01. 5 Amazon Basics Lightweight Super Soft Easy Care Microfiber Bed Sheet Set with Two Pillowcases - Twin, Bright White'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Soft and durable. Soft $28.01. 5 Amazon Basics Lightweight Super Soft Easy Care Microfiber Bed Sheet Set with Two Pillowcases - Twin, Bright White\n",
      "Predicted Answer: White\n",
      "F1 Score: 0.08695652173913045, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0002939965343102813, 'start': 0, 'end': 4, 'answer': 'BEST'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'BEST SHEETS EVER IMAGINABLE!. I am 42 and have had some expensive sheets...<br />Trying these out was the BEST decision ever!<br />They are so soft an'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: BEST SHEETS EVER IMAGINABLE!. I am 42 and have had some expensive sheets...<br />Trying these out was the BEST decision ever!<br />They are so soft an\n",
      "Predicted Answer: BEST\n",
      "F1 Score: 0.07692307692307693, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9984631538391113, 'start': 507, 'end': 508, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 507, 'text': '5'}\n",
      "Question: What was the average rating for productHOMEIDEAS Queen Size Bed Sheets - 4 Piece Set (Gray) - Extra Soft Brushed Microfiber 1800 Bedding Sheets, Deep Pocket, Wrinkle & Fade Free?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00019769016944337636, 'start': 0, 'end': 4, 'answer': 'Well'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Well priced and really soft and comfortable. Love thse sheets. Fit great, comfortable and washes well. $24.99. 5 1500 Supreme Collection Twin XL Sheet'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Well priced and really soft and comfortable. Love thse sheets. Fit great, comfortable and washes well. $24.99. 5 1500 Supreme Collection Twin XL Sheet\n",
      "Predicted Answer: Well\n",
      "F1 Score: 0.08695652173913045, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9994921088218689, 'start': 412, 'end': 413, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 412, 'text': '5'}\n",
      "Question: What was the average rating for productSONORO KATE Bed Sheet Set Super Soft Microfiber 1800 Thread Count Luxury Egyptian Sheets Fit 18-24 Inch Deep Pocket Mattress Wrinkle-3 Piece (Lake Blue, California King)?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00020028172002639621, 'start': 0, 'end': 3, 'answer': 'Bad'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': \"Bad sizing. Bed sheet sizing must be off/wrong. I ordered a queen and it even said queen on the tag but it's a good foot too long for the bed. Obv see\"}\n",
      "Question: Why did the customer rate this product 2 stars?\n",
      "True Answer: Bad sizing. Bed sheet sizing must be off/wrong. I ordered a queen and it even said queen on the tag but it's a good foot too long for the bed. Obv see\n",
      "Predicted Answer: Bad\n",
      "F1 Score: 0.06666666666666667, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9960727095603943, 'start': 154, 'end': 155, 'answer': '4'}\n",
      "True Answer (raw): {'answer_start': 154, 'text': '4'}\n",
      "Question: What was the average rating for productAmazon Basics Lightweight Super Soft Easy Care Microfiber Bed Sheet Set with Two Pillowcases - Twin, Bright White?\n",
      "True Answer: 4\n",
      "Predicted Answer: 4\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00015022529987618327, 'start': 0, 'end': 4, 'answer': 'Nice'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Nice product. Very nice sheets. Only thing that was incorrect was the label on product. It said its Normal Pocket sheet but I ordered and received Dee'}\n",
      "Question: Why did the customer rate this product 4 stars?\n",
      "True Answer: Nice product. Very nice sheets. Only thing that was incorrect was the label on product. It said its Normal Pocket sheet but I ordered and received Dee\n",
      "Predicted Answer: Nice\n",
      "F1 Score: 0.07692307692307693, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9992268681526184, 'start': 95, 'end': 96, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 95, 'text': '5'}\n",
      "Question: What was the average rating for productMellanni RV Bedding Short Queen - Double Brushed Microfiber Camper Bunk Sheets - Durable and Breathable Cooling Sheets - Fits Mattress Up to 10'' - Deep Pocket Queen Sheet Sets (Short Queen, Spa Blue)?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0004132987523917109, 'start': 0, 'end': 4, 'answer': 'Good'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': \"Good Housekeeping recommended brand. Good Housekeeping recommended brand?  They're now off my list of opinions to trust.  These are OK so far but the \"}\n",
      "Question: Why did the customer rate this product 3 stars?\n",
      "True Answer: Good Housekeeping recommended brand. Good Housekeeping recommended brand?  They're now off my list of opinions to trust.  These are OK so far but the \n",
      "Predicted Answer: Good\n",
      "F1 Score: 0.0909090909090909, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00030599956517107785, 'start': 0, 'end': 5, 'answer': 'Cheap'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': \"Cheap. We've used these sheet for 1 week so far. I have to say they are feel very soft which I love. But they are very very thin/see through. The flat\"}\n",
      "Question: Why did the customer rate this product 2 stars?\n",
      "True Answer: Cheap. We've used these sheet for 1 week so far. I have to say they are feel very soft which I love. But they are very very thin/see through. The flat\n",
      "Predicted Answer: Cheap\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00018035438552033156, 'start': 0, 'end': 4, 'answer': 'Soft'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Soft and comfy. I love the color and the softness of these sheets! They were just as I wanted and what I expected $38.99. 5 Full Size Sheet Set - 6 Pi'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Soft and comfy. I love the color and the softness of these sheets! They were just as I wanted and what I expected $38.99. 5 Full Size Sheet Set - 6 Pi\n",
      "Predicted Answer: Soft\n",
      "F1 Score: 0.07142857142857142, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0002883154957089573, 'start': 149, 'end': 155, 'answer': 'Pocket'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Yes.. Great price. Great sheets. So far, so good. $21.99. 5 Shilucheng Bed Sheet Set Microfiber 1800 Threads Egyptian Super Soft Sheets 16-Inch Deep P'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Yes.. Great price. Great sheets. So far, so good. $21.99. 5 Shilucheng Bed Sheet Set Microfiber 1800 Threads Egyptian Super Soft Sheets 16-Inch Deep P\n",
      "Predicted Answer: Pocket\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0002238269808003679, 'start': 0, 'end': 9, 'answer': 'Wonderful'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Wonderful sheets. Great sheets. $43.99. 5 Threadmill Cotton Full Size Sheet set| 100% Cotton Sheets for Full Size Bed | Solid Sateen Full Bed Sheets S'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Wonderful sheets. Great sheets. $43.99. 5 Threadmill Cotton Full Size Sheet set| 100% Cotton Sheets for Full Size Bed | Solid Sateen Full Bed Sheets S\n",
      "Predicted Answer: Wonderful\n",
      "F1 Score: 0.1, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9996040463447571, 'start': 522, 'end': 523, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 522, 'text': '5'}\n",
      "Question: What was the average rating for productElegant Comfort Luxury Soft 1500 Thread Count Egyptian 4-Piece Premium Hotel Quality Wrinkle Resistant Coziest Bedding Set, All Around Elastic Fitted Sheet, Deep Pocket up to 16inch, Queen, Red?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9992392659187317, 'start': 37, 'end': 38, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 37, 'text': '5'}\n",
      "Question: What was the average rating for productSONORO KATE Bed Sheet Set Super Soft Microfiber 1800 Thread Count Luxury Egyptian Sheets 16-Inch Deep Pocket，Wrinkle-3 Piece (Burgundy, Twin XL)?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9992538094520569, 'start': 166, 'end': 167, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 166, 'text': '5'}\n",
      "Question: What was the average rating for productMellanni RV Bedding Short Queen - Double Brushed Microfiber Camper Bunk Sheets - Durable and Breathable Cooling Sheets - Fits Mattress Up to 10'' - Deep Pocket Queen Sheet Sets (Short Queen, Spa Blue)?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9993798136711121, 'start': 55, 'end': 56, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 55, 'text': '5'}\n",
      "Question: What was the average rating for productFull Size Sheet Set - 6 Piece Set - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - Breathable & Cooling Sheets - Wrinkle Free - Comfy - Beige Tan Bed Sheets - Fulls Sheets - 6 PC?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.7050876021385193, 'start': 150, 'end': 152, 'answer': '25'}\n",
      "True Answer (raw): {'answer_start': 151, 'text': '5'}\n",
      "Question: What was the average rating for productRV Short Queen Sheet Set 400 Thread Count Egyptian Cotton Sheets for RV Camper Short Queen Size Gray 4 PCs Sheet Sets 15\" Deep Pocket Short Queen (60\" X 75\") Dark Grey?\n",
      "True Answer: 5\n",
      "Predicted Answer: 25\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0002667554363142699, 'start': 0, 'end': 5, 'answer': 'Great'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Great for kids bed. Bought for 9 year old son, great buy he likes them! Item is as described wish they were a little thicker material but works for hi'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Great for kids bed. Bought for 9 year old son, great buy he likes them! Item is as described wish they were a little thicker material but works for hi\n",
      "Predicted Answer: Great\n",
      "F1 Score: 0.0689655172413793, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9993786215782166, 'start': 50, 'end': 51, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 50, 'text': '5'}\n",
      "Question: What was the average rating for productMellanni RV Bedding Short Queen - Double Brushed Microfiber Camper Bunk Sheets - Durable and Breathable Cooling Sheets - Fits Mattress Up to 10'' - Deep Pocket Queen Sheet Sets (Short Queen, Spa Blue)?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9996414184570312, 'start': 303, 'end': 304, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 303, 'text': '5'}\n",
      "Question: What was the average rating for productFull Size Sheet Set - 6 Piece Set - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - Breathable & Cooling Sheets - Wrinkle Free - Comfy - Beige Tan Bed Sheets - Fulls Sheets - 6 PC?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.32499122619628906, 'start': 172, 'end': 174, 'answer': '63'}\n",
      "True Answer (raw): {'answer_start': 173, 'text': '3'}\n",
      "Question: What was the average rating for productMayfair Linen 5 Star Luxury Hotel King Size 100% Cotton Sheets - Egyptian Cotton Quality 600 TC Sheets for King Bed - 4 Piece Bedding Set with Deep Pocket, Breathable & Cooling Bedsheet (Ivory)?\n",
      "True Answer: 3\n",
      "Predicted Answer: 63\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.999378502368927, 'start': 123, 'end': 124, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 123, 'text': '5'}\n",
      "Question: What was the average rating for product1500 Supreme Collection Twin XL Sheet Sets Lilac - 3 Piece Bed Sheets and Pillowcase Set for Twin XL Mattress - Extra Soft, Elastic Corner Straps, Deep Pocket Sheets, Twin XL Lilac?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00020739423052873462, 'start': 0, 'end': 3, 'answer': 'ARE'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': \"ARE THEY SECOND'S?. Bought 3 different sets.  Washed one. Came out of washer and dryer full of wrinkles--so much for wrinkle free.  Also they had pecu\"}\n",
      "Question: Why did the customer rate this product 1 stars?\n",
      "True Answer: ARE THEY SECOND'S?. Bought 3 different sets.  Washed one. Came out of washer and dryer full of wrinkles--so much for wrinkle free.  Also they had pecu\n",
      "Predicted Answer: ARE\n",
      "F1 Score: 0.07692307692307693, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9994487762451172, 'start': 68, 'end': 69, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 68, 'text': '5'}\n",
      "Question: What was the average rating for productKing Size Sheet Set - Breathable & Cooling - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - 4 Piece Set - Wrinkle Free - Comfy - Dark Grey Bed Sheets - Kings Sheets - Fitted Sheets?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00033495729439891875, 'start': 148, 'end': 156, 'answer': 'mattress'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Not deep enough pockets. These sheets definitely are not 16 inch deep pockets.  They barely fit on my queen mattress.  If you have a topper on your ma'}\n",
      "Question: Why did the customer rate this product 2 stars?\n",
      "True Answer: Not deep enough pockets. These sheets definitely are not 16 inch deep pockets.  They barely fit on my queen mattress.  If you have a topper on your ma\n",
      "Predicted Answer: mattress\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9992305636405945, 'start': 162, 'end': 163, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 162, 'text': '5'}\n",
      "Question: What was the average rating for productKing Size Sheet Set - Breathable & Cooling - Hotel Luxury Bed Sheets - Extra Soft - Deep Pockets - Easy Fit - 4 Piece Set - Wrinkle Free - Comfy - Dark Grey Bed Sheets - Kings Sheets - Fitted Sheets?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.0005133470403961837, 'start': 140, 'end': 145, 'answer': 'White'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Five Stars. Perfect!! $28.01. 5 Amazon Basics Lightweight Super Soft Easy Care Microfiber Bed Sheet Set with Two Pillowcases - Twin, Bright White'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Five Stars. Perfect!! $28.01. 5 Amazon Basics Lightweight Super Soft Easy Care Microfiber Bed Sheet Set with Two Pillowcases - Twin, Bright White\n",
      "Predicted Answer: White\n",
      "F1 Score: 0.08333333333333333, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00010150523303309456, 'start': 147, 'end': 152, 'answer': 'Super'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Great if not gashed. These are really soft but one arrived with a gash in it which is why I gave only 2 stars. $28.01. 2 Amazon Basics Lightweight Sup'}\n",
      "Question: Why did the customer rate this product 2 stars?\n",
      "True Answer: Great if not gashed. These are really soft but one arrived with a gash in it which is why I gave only 2 stars. $28.01. 2 Amazon Basics Lightweight Sup\n",
      "Predicted Answer: Super\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.00015790130419190973, 'start': 147, 'end': 156, 'answer': 'expensive'}\n",
      "True Answer (raw): {'answer_start': 0, 'text': 'Wonderful sheet set. Wonderful sheet set. I purchased it for my Sleep Number Split King Adjustable bed, and they fit perfectly, and were much less exp'}\n",
      "Question: Why did the customer rate this product 5 stars?\n",
      "True Answer: Wonderful sheet set. Wonderful sheet set. I purchased it for my Sleep Number Split King Adjustable bed, and they fit perfectly, and were much less exp\n",
      "Predicted Answer: expensive\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9996470808982849, 'start': 108, 'end': 110, 'answer': '24'}\n",
      "True Answer (raw): {'answer_start': 109, 'text': '4'}\n",
      "Question: What was the average rating for product1500 Supreme Collection Twin XL Sheet Sets Lilac - 3 Piece Bed Sheets and Pillowcase Set for Twin XL Mattress - Extra Soft, Elastic Corner Straps, Deep Pocket Sheets, Twin XL Lilac?\n",
      "True Answer: 4\n",
      "Predicted Answer: 24\n",
      "F1 Score: 0, EM Score: 0\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.9996598362922668, 'start': 103, 'end': 104, 'answer': '5'}\n",
      "True Answer (raw): {'answer_start': 103, 'text': '5'}\n",
      "Question: What was the average rating for productCalifornia Design Den Luxury 100% Cotton Sateen Buttery Soft 800 Thread Count Bed Sheet Set, Beats Fake Egyptian Claim, Durable Deep Pocket Fitted Sheet (King, Pastel Blue - Steel)?\n",
      "True Answer: 5\n",
      "Predicted Answer: 5\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Predicted Answer (raw): {'score': 0.999210774898529, 'start': 310, 'end': 311, 'answer': '2'}\n",
      "True Answer (raw): {'answer_start': 310, 'text': '2'}\n",
      "Question: What was the average rating for productSatin Sheets California King [4-Piece, White] Luxury Silky Bed Sheets - Extra Soft 1800 Microfiber Sheet Set, Wrinkle, Fade, Stain Resistant - Deep Pocket Fitted Sheet, Flat Sheet, Pillow Cases?\n",
      "True Answer: 2\n",
      "Predicted Answer: 2\n",
      "F1 Score: 1.0, EM Score: 1\n",
      "----\n",
      "Average F1 Score: 0.4403940084680714\n",
      "Average Exact Match Score: 0.41\n"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import f1_score\n",
    "# Function to calculate F1 score based on word overlap\n",
    "def compute_f1_score(predicted_answer, true_answer):\n",
    "    # Tokenize the answers by splitting them into words\n",
    "    pred_tokens = set(predicted_answer.split())\n",
    "    true_tokens = set(true_answer.split())\n",
    "    \n",
    "    # Calculate precision, recall, and F1 score using word overlap\n",
    "    intersection = len(pred_tokens.intersection(true_tokens))\n",
    "    if intersection == 0:\n",
    "        return 0\n",
    "    precision = intersection / len(pred_tokens)\n",
    "    recall = intersection / len(true_tokens)\n",
    "    \n",
    "    # Calculate F1 as the harmonic mean of precision and recall\n",
    "    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0\n",
    "    return f1\n",
    "\n",
    "\n",
    "\n",
    "f1_scores = []\n",
    "em_scores = []\n",
    "\n",
    "# Evaluate on the test dataset\n",
    "for example in evaluatetest:\n",
    "    question = example['question']\n",
    "    context = example['context']\n",
    "    true_answer = example['answer']\n",
    "\n",
    "    # Get the predicted answer\n",
    "    result = qa_pipeline(question=question, context=context)\n",
    "    predicted_answer = result['answer']\n",
    "\n",
    "    # Debugging: Print the structure of predicted_answer and true_answer\n",
    "    print(f\"Predicted Answer (raw): {result}\")\n",
    "    print(f\"True Answer (raw): {true_answer}\")\n",
    "    \n",
    "    # Ensure both answers are strings\n",
    "    if isinstance(predicted_answer, dict):\n",
    "        predicted_answer = predicted_answer.get('answer', '')  # Extract the answer from the dictionary\n",
    "    if isinstance(true_answer, dict):\n",
    "        true_answer = true_answer.get('text', '')  # If true_answer is also a dictionary, extract the answer\n",
    "    \n",
    "\n",
    "    # Calculate F1 and EM\n",
    "    f1 = compute_f1_score(predicted_answer,true_answer )\n",
    "    f1_scores.append(f1)\n",
    "        \n",
    "    em = 1 if predicted_answer.strip().lower() == true_answer.strip().lower() else 0\n",
    "    em_scores.append(em)\n",
    "\n",
    "    # Print or calculate metrics (e.g., F1, Exact Match)\n",
    "    print(f\"Question: {question}\")\n",
    "    print(f\"True Answer: {true_answer}\")\n",
    "    print(f\"Predicted Answer: {predicted_answer}\")\n",
    "    print(f\"F1 Score: {f1}, EM Score: {em}\")\n",
    "    print(\"----\")\n",
    "\n",
    "\n",
    "# Calculate average F1 and EM scores\n",
    "avg_f1 = sum(f1_scores) / len(f1_scores)\n",
    "avg_em = sum(em_scores) / len(em_scores)\n",
    "print(f\"Average F1 Score: {avg_f1}\")\n",
    "print(f\"Average Exact Match Score: {avg_em}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "dev",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
